services:
  - type: web
    name: learnova-ai-backend
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
